THIS_FILE_ABSOLUTE_LOCATION=$(realpath ${BASH_SOURCE})
WORKING_DIRECTORY="$(dirname "${THIS_FILE_ABSOLUTE_LOCATION}")";
#FILE_NAME="$(basename "${THIS_FILE_ABSOLUTE_LOCATION}")"
echo ${WORKING_DIRECTORY}